// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("namecheap");

/**
 * A registered apiuser for namecheap
 */
export declare const apiUser: string | undefined;
Object.defineProperty(exports, "apiUser", {
    get() {
        return __config.get("apiUser");
    },
    enumerable: true,
});

/**
 * IP addess of the machine running terraform
 */
export declare const ip: string | undefined;
Object.defineProperty(exports, "ip", {
    get() {
        return __config.get("ip");
    },
    enumerable: true,
});

/**
 * The token key for API operations.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

/**
 * If true, use the namecheap sandbox
 */
export declare const useSandbox: boolean | undefined;
Object.defineProperty(exports, "useSandbox", {
    get() {
        return __config.getObject<boolean>("useSandbox");
    },
    enumerable: true,
});

/**
 * A registered username for namecheap
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

