name: release

on:
  push:
    workflow_dispatch:
    tags:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21.0"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
          scope: "@sst-provider"

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.11.0
        with:
          repo: pulumi/pulumictl

      - name: Go Mod
        working-directory: ./provider
        run: go mod download

      - run: make build_nodejs

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.SST_GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN_SST_PROVIDER }}
          package: ${{ github.workspace }}/sdk/nodejs/bin/package.json
