// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the namecheap package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'namecheap';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * A registered apiuser for namecheap
     */
    public readonly apiUser!: pulumi.Output<string>;
    /**
     * IP addess of the machine running terraform
     */
    public readonly ip!: pulumi.Output<string>;
    /**
     * The token key for API operations.
     */
    public readonly token!: pulumi.Output<string>;
    /**
     * A registered username for namecheap
     */
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.apiUser === undefined) && !opts.urn) {
                throw new Error("Missing required property 'apiUser'");
            }
            if ((!args || args.ip === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ip'");
            }
            if ((!args || args.token === undefined) && !opts.urn) {
                throw new Error("Missing required property 'token'");
            }
            if ((!args || args.username === undefined) && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["apiUser"] = args ? args.apiUser : undefined;
            resourceInputs["ip"] = args ? args.ip : undefined;
            resourceInputs["token"] = args ? args.token : undefined;
            resourceInputs["useSandbox"] = pulumi.output(args ? args.useSandbox : undefined).apply(JSON.stringify);
            resourceInputs["username"] = args ? args.username : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * A registered apiuser for namecheap
     */
    apiUser: pulumi.Input<string>;
    /**
     * IP addess of the machine running terraform
     */
    ip: pulumi.Input<string>;
    /**
     * The token key for API operations.
     */
    token: pulumi.Input<string>;
    /**
     * If true, use the namecheap sandbox
     */
    useSandbox?: pulumi.Input<boolean>;
    /**
     * A registered username for namecheap
     */
    username: pulumi.Input<string>;
}
